### ISSUE TITLE
location of confidence model score？

### ISSUE THREAD

**Issue by HeJunhong1107** [ketatam/DiffDock-PP#2]
Thanks for the amazing work，and I have finished the test demo of DIPS，Do there have a specific file for users  to check the  confidence scores of protein pairs？

**Comment by HeJunhong1107** [comment]
ps：Dose there exist a cutoff for “good” confidence score？

**Comment by ketatam** [comment]
Hi! Thanks a lot for your interest in our work. Great to hear that you have finished the test demo of DIPS.

Currently, we do not have any such file that allows for checking the confidence scores of protein pairs. Could you elaborate more on the format of such a file and how you would use it?

To answer your second question, the confidence score is the output of the last layer of a binary classifier (the logit) that would be passed through a sigmoid to get a probability value between 0 and 1. Therefore, a value of 0 for the confidence score corresponds to a probability value of 0.5, which is usually considered a cutoff for a "good" value but is however not fixed and you can choose any other value with this logic, depending on how you wanna set the threshold probability. However, note that since we are ranking the generated poses by their scores, the actual values do not really matter, only their order does (that is also why we de not apply the last sigmoid activation and we just rank the outputs of that last linear layer)

Hope this helps

**Comment by HeJunhong1107** [comment]
thanks for your kind reply～
