### ISSUE TITLE
DB5Loader single-pair PDB error

### ISSUE THREAD

**Issue by slieped** [ketatam/DiffDock-PP#4]
Hi (again!)

I have been playing around with your code.
Followed your suggestions using the DB5Loader loader and did the trick!

Found that, if one uses a .csv file with only ONE pair of pdbs (i.e one line) the code fails.
Concretely, the error rises  at  `data_train_utils.compute_embeddings`, the torch.cat [line 350, 350] function.

With 2+ pairs of .pdb script works correctly. 

Possible solution:
Simple check of  `rec_reps` dimensions before running the concatanation.

Let me know if you require further info

Victor M

**Comment by ketatam** [comment]
Hi,

Thanks a lot for pointing out this issue. 

It has now been fixed by removing the call to `squeeze()` in [this line](https://github.com/ketatam/DiffDock-PP/blob/main/src/main_inf.py#L362)

I have tested it this way with a single file and it worked, let me know if you still encounter any issues.

I will close the issue for now :)
