### ISSUE TITLE
PDB viz code

### ISSUE THREAD

**Issue by slieped** [ketatam/DiffDock-PP#6]
Hi (again)

It seems that the code for visualization (in main_inf.py) is commented. 
Not clear what should be un-commented in order to visualze the output .pdb of the estimates.
Inisghts?

V

**Comment by ketatam** [comment]
Hi!

the commented code is just legacy code from previous experiments and is not meant for visualization, sorry for the confusion.

In order to get the visualization, you should pass the `visualize_first_n_samples` and `visualization_dir` arguments to the `sample` function in [this line](https://github.com/ketatam/DiffDock-PP/blob/main/src/main_inf.py#L337), for example. This will save the pdb files of the complex at each time step of the reverse diffusion process to the `visualization` folder.

Let me know if you need any further help.
